#!/usr/bin/env python

import os, sys, re

incre = re.compile(r'# *include *"(.+\.h)"')

dep = open('depends', 'w')

ignored_headers = ('zlib.h', 'OpenMM.h', 'netcdf.h')

for f in os.listdir('.'):
    if f.endswith('.F90') or f.endswith('.cpp'):
        if f in ignored_headers: continue
        mydep = [f]
        fd = open(f, 'r')
        for line in fd:
            if incre.match(line):
                d = incre.match(line).groups()[0]
                if not d in mydep and not d in ignored_headers:
                    mydep.append('../include/%s' % d)
        if mydep: dep.write('%s: %s\n' % (f.replace('.cpp', '.o').replace('.F90', '.o'), ' '.join(mydep)))

for f in os.listdir('../include/amber') + ['Amber.h']:
    if f in ignored_headers: continue
    mydep = []
    if f == 'Amber.h':
        f = os.path.join('..', 'include', f)
    else:
        f = os.path.join('..', 'include', 'amber', f)
    fd = open(f, 'r')
    for line in fd:
        if incre.match(line):
            d = incre.match(line).groups()[0]
            if not d in mydep and not d in ignored_headers:
                mydep.append('../include/amber/%s' % os.path.split(d)[1])
    if mydep: dep.write('%s: %s\n' % (f, ' '.join(mydep)))

dep.close()
